version: "3"
services:

  redis:
    image: redis:alpine
    networks:
      - front
    deploy:
      replicas: 1

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5000:80
    networks:
      - front
    deploy:
      replicas: 2

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 5001:80
    networks:
      - back
    deploy:
      replicas: 1

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - front
      - back
    deploy:
      replicas: 1

networks:
  front:
  back:

volumes:
  db-data:
